export * from "./schools";
export * from "./classes";
export * from "./students";
export * from "./terms";
export * from "./subjects";
export * from "./grading";
export * from "./psychomotor";
export * from "./scores";
export * from "./reportcards";
